pre_install do |installer|
    $RNMBGL.pre_install(installer)
    ... other pre install hooks
  end
post_install do |installer|
    $RNMBGL.post_install(installer)
    ... other post install hooks
  end

